services:
  registry:
    image: distribution/distribution:3.0.0
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./config.yml:/etc/distribution/config.yml:ro
    environment:
      REGISTRY_STORAGE_S3_REGION: ${AWS_REGION}
      REGISTRY_STORAGE_S3_BUCKET: distribution-registry-${AWS_ACCOUNT_ID}
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    env_file:
      - local.env
